version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10
        environment:
          PG_CONNECTION_STRING: postgresql://observe:observe@localhost/circle_test
      - image: circleci/postgres:11-alpine-postgis
        environment:
          POSTGRES_USER: observe
          POSTGRES_PASSWORD: observe

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Run tests
          command: npm run test
  deploy-staging:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install EB CLI (Elastic Beanstalk)
          command: pip install awsebcli --upgrade --user
      - run:
          name: Configure  EB CLI
          command: eb init --verbose --region us-east-1 observe-staging          
      - run:
          name: Deploy
          command: eb deploy observe-api-staging-env

workflows:
  version: 2
  test-and-deploy:
    jobs:
      # - test
      - deploy-staging
      # - deploy-staging:
          # requires:
          #   - lint
          # filters:
          #   branches:
          #     only: develop
